# Generated by Django 3.0.7 on 2020-06-12 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20200417_1842'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(blank=True, null=True)),
                ('we', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Weather',
            },
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
