# Generated by Django 3.0.7 on 2020-06-12 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20200612_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='city',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='we',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
